name: Sähkövene
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6349
title: Nauti veneilystä ilman polttoaineen käryä
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#598794'
    - '#f0f1f5'
    - '#03080e'
    - '#2d464a'
    - '#b34e32'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
