name: sahkovene
favicon: null
layout_spectrum: 0.7944
typography_spectrum: 0.6349
title: Sähköveneilyn vallankumous
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e5e3'
    - '#5f6e77'
    - '#000004'
    - '#80453f'
    - '#fe8f6a'
  brandStrength: 0.45309819048270583
  lightness: 0.6140017216093838
  saturation: 0.7193302758969367
  rhythmicContrast: 0.48525677854195237
purpose: []
